### PR TITLE
Refactor: Modified type hint for 'perform_get_light_state' to expect …

### PR DESCRIPTION
**Pull request by qwease**
…correct type.

## Proposed change

This pull request is the solution to the issue: https://sonarcloud.io/project/issues?open=AZIe47QO2tbBnOef_EW6&id=karthik4959_core&tab=code
This version allows you to pass either an integer or an HTTPStatus enum member, providing more flexibility while maintaining type safety.
To achieve this, I added "int" type to the function's type hint, so the variable(expected_status) now accepts both types. This not only shows that the variable is indeed a integer, but also keeps the representation of it.
The reason why I don't straightly delete HTTPStatus is that I want to keep using HTTPStatus in home-assistant codebase for clarity and consistency, since it suggests that the integer is actually representing a HTTP status code.
All tests passed for the change.

## Type of change

- [ ] Dependency upgrade
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New integration (thank you!)
- [ ] New feature (which adds functionality to an existing integration)
- [ ] Deprecation (breaking change to happen in the future)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue: 
- Link to documentation pull request: 

## Checklist

- [x] The code change is tested and works locally.
- [x] Local tests pass. **Your PR cannot be merged unless tests pass**
- [x] There is no commented out code in this PR.
- [x] I have followed the [development checklist][dev-checklist]
- [x] I have followed the [perfect PR recommendations][perfect-pr]
- [x] The code has been formatted using Ruff (`ruff format homeassistant tests`)
- [x] Tests have been added to verify that the new code works.

If user exposed functionality or configuration variables are added/changed:

- [ ] Documentation added/updated for [www.home-assistant.io][docs-repository]

If the code communicates with devices, web services, or third-party tools:

- [ ] The [manifest file][manifest-docs] has all fields filled out correctly.  
      Updated and included derived files by running: `python3 -m script.hassfest`.
- [ ] New or updated dependencies have been added to `requirements_all.txt`.  
      Updated by running `python3 -m script.gen_requirements_all`.
- [ ] For the updated dependencies - a link to the changelog, or at minimum a diff between library versions is added to the PR description.

To help with the load of incoming pull requests:

- [ ] I have reviewed two other [open pull requests][prs] in this repository.

[prs]: https://github.com/home-assistant/core/pulls?q=is%3Aopen+is%3Apr+-author%3A%40me+-draft%3Atrue+-label%3Awaiting-for-upstream+sort%3Acreated-desc+review%3Anone+-status%3Afailure

[dev-checklist]: https://developers.home-assistant.io/docs/development_checklist/
[manifest-docs]: https://developers.home-assistant.io/docs/creating_integration_manifest/
[quality-scale]: https://developers.home-assistant.io/docs/integration_quality_scale_index/
[docs-repository]: https://github.com/home-assistant/home-assistant.io
[perfect-pr]: https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr

### CODE REVIEW

**Comment by qwease** [comment]
Reason why I chose the issue: Have one of the top references; Multiple issues in tests point to the function definition; Testable (have test file that test this); The definition of the function can be misleading; HTTPStatus is actually a class, but the input is one of the HTTP Code(int) it holds.

**Comment by qwease** [comment]
pip install -r requirements_test_all.txt
image
pytest -x tests/components/emulated_hue/test_hue_api.py
image

**Comment by simaremare** [comment]
The solution looks good, but it introduces new issues.

**Comment by qwease** [comment]
Tried to resolve new issues in new commits.

**Pull request merged**
